### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by alekbarszczewski** [posabsolute/redux-flash-notification#1]
Hello, I tried to install your module, however react/babel loaders fail on this line https://github.com/posabsolute/redux-flash-notification/blob/master/src/component/growler.js#L12 - `@` keyword is not recognized by them on this line:

```
@connect(mapStateToProps, mapDispatchToProps)
```

What does `@` mean? It's not JS/JSX keyword I guess, I know it only from coffee script.
Maybe you could write a build script that would generate dist version of your plugin that you would push to npm registry so it won't be necessary to compile it using additional loaders?

Your module look cool by the way, looking forward to be able to use it in my project, thanks.

**Comment by posabsolute** [comment]
sorry for the late comment, it means you did not enable es7 decorators in your babel config, you need to add stage 0  to your config
babel5:  
`loaders:['react-hot', 'babel?stage=0&loose[]=es6.modules']`
