### ISSUE TITLE
Add body class when flash message appears

### ISSUE THREAD

**Issue by bkrall** [posabsolute/redux-flash-notification#4]
I'd like to have a corresponding body class when a flash message show and hide when the message disappears.  Similar to Bootstrap when a modal shows and hides.

Would you recommend doing it this way?
http://jaketrent.com/post/update-body-class-react/

**Comment by posabsolute** [comment]
yes that would be what I recommend

Expose the growler state in your app container

```
const mapStateToProps = state => ({
  growler: state.growler,
});
```

then something like 

```
var growlerState =  this.props.growler.status === 'show';
document.body.classList.toggle('modal--active', growlerState);
```

I'm open to other suggestion? I could handle that in the plugin with a config prop

**Comment by bkrall** [comment]
I was actually able to do it w/ CSS as is:

```
    // Flash message positioning
    .growler.growler--error ~ section {
        margin-top: 70px;
        transition: all .2s linear;
    }


    // Hidden
    .growler.growler--error.growler--hidden ~ section,
    .growler.growler--error.growler--hiding ~ section {
        margin-top: 0;
    }

```

**Comment by posabsolute** [comment]
Interesting, I will look at integrating that behavior in the future as an option. Thanks!
